### ISSUE TITLE
code is dead

### ISSUE THREAD

**Issue by nl1536** [aefreedman/SP2018_IntermediateGameDev#3]
ok so my code was working, and then i added some bools to it, and then it stopped working, so i said "ok, i'll just take out my bools and see if that works again" and so i did but i guess once it dies it dies for good bc it refuses to work now even though it's the same exact code as before when it was working.

my code that was working but now is not in its ENTIRETY:

```using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class playerMovement : MonoBehaviour
{

	// Use this for initialization
	void Start ()
	{
		
	}
	
	// Update is called once per frame
	void Update ()
	{

		float yAxisRotation = 1.5f;
		float movementSpeed = 10f;

		// MOVEMENT INPUT <WASD + SPACEBAR>

		if (Input.GetKey(KeyCode.W))
		{
			transform.position += transform.forward * Time.deltaTime * movementSpeed;
		}

		if (Input.GetKey(KeyCode.A))
		{
			transform.position -= transform.right * Time.deltaTime * movementSpeed;
		}

		if (Input.GetKey(KeyCode.S))
		{
			transform.position -= transform.forward * Time.deltaTime * movementSpeed;
		}

		if (Input.GetKey(KeyCode.D))
		{
			transform.position += transform.right * Time.deltaTime * movementSpeed;
		}
		
		// ROTATION INPUT <ARROW KEYS>

		if (Input.GetKey(KeyCode.LeftArrow))
		{
			GetComponent<Transform>().eulerAngles += new Vector3(0f, -yAxisRotation, 0f);
		}

		if (Input.GetKey(KeyCode.RightArrow))
		{
			GetComponent<Transform>().eulerAngles += new Vector3(0f, yAxisRotation, 0f);
		}
		
		// HINTS

		if (GetComponent<Transform>().position.x >= 19f &&
		    GetComponent<Transform>().position.x <= 30f &&
		    GetComponent<Transform>().position.z >= 25f &&
		    GetComponent<Transform>().position.z <= 40f)
		{
			Debug.Log("start");
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "Eurgh... Where am I...?";
		}
		else
		{
			Debug.Log("not start");
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "";
		}

		if (GetComponent<Transform>().position.x >= 275f &&
		    GetComponent<Transform>().position.x <= 290f &&
		    GetComponent<Transform>().position.z >= 275f &&
		    GetComponent<Transform>().position.z <= 280f)
		{
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "Hmm... How do I help?";
		}
		else
		{
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "";
		}
		
		if (GetComponent<Transform>().position.x >= 35f &&
		    GetComponent<Transform>().position.x <= 65f &&
		    GetComponent<Transform>().position.z >= 440f &&
		    GetComponent<Transform>().position.z <= 465f )
		{
			Debug.Log("found core");
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "Hey! My energy core!";
		}
		else
		{
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "";
		}
		
		if (GetComponent<Transform>().position.x >= 430f &&
		    GetComponent<Transform>().position.x <= 450f &&
		    GetComponent<Transform>().position.z >= 440f &&
		    GetComponent<Transform>().position.z <= 470f)
		{
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "Look! My legs!";
		}
		else
		{
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "";
		}
		
		if (GetComponent<Transform>().position.x >= 430f &&
		    GetComponent<Transform>().position.x <= 450f &&
		    GetComponent<Transform>().position.z >= 30f &&
		    GetComponent<Transform>().position.z <= 70f)
		{
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "Oh! My arms!";
		}
		else
		{
			GameObject.FindWithTag("UIText").GetComponent<Text>().text = "";
		}
	}
}
```

the uitext just... won't render anymore, even if the debug log says it should.

hlep

**Comment by nl1536** [comment]
(also i'm sorry the code is so bad but i promise even though i was p much brute forcing everything it was absolutely WORKING with this exact script until i guess it just didn't feel like it anymore)

**Comment by nl1536** [comment]
actually to clarify the movement and stuff is all working properly, it's just the uitext that isn't showing up

**Comment by aefreedman** [comment]
Code is not magic. If it was working before you made a change and you reverted it but it no longer works then you made a mistake somewhere. Are you using version control for this project? You are probably not, because you are asking this question.

Are you seeing any errors in your console when you run the scene?

Also make sure that you did not change something else in the scene that would make the UI invisible.

If everything else looks like it should work, restart Unity and Rider and run the scene before trying something else.

**Comment by aefreedman** [comment]
You are also using a lot of `Get...()` calls. I would not be surprised if you have a null reference.

Also, use variables.

**Comment by nl1536** [comment]
no errors in the console, just the debug log doing exactly what it should.
and no, nothing in the scene was changed, just the code.

i was just wondering if you could see a mistake in the code, since i went through it several times and didn't see anything despite it not working. guess not.

and the get...() calls were all working and weren't touched when the code changed, so i'm pretty sure that's not the problem.

i've already restarted unity once but i'll try doing that again along with restarting rider once i get off of work.

**Comment by aefreedman** [comment]
There is nothing in your code that affects the display of the text other than changing the string that is displayed. Make sure you are not conflating the object not rendering and the text object displaying an empty string.

Make sure that you are not using multiple objects with the same tag you are searching for. Also don't find game objects by tag or name. It's bad. Don't do it. Use a field and store the reference in the script.

Make sure you have also enabled the console to display errors and are not hiding them.

If you inspect the text object when the code is running and the text field is changing, then there is a problem somewhere else.

If you inspect the code object and the text field does not change, then your logic is probably incorrect. If you're also getting an error from the script, then that is probably the problem. If you are not getting an error then you are likely making an incorrect assumption about how your code works, or there is a problem with your scene setup unrelated to the script.

If nothing else works, make a super simple script that simply changes the text on the UIText and make sure you are doing that correctly.

**Comment by aefreedman** [comment]
Oh that's why. 

Review how if statements work. Go back to the questions from the worksheet that we talked about in class.

Your text string is always empty because each if...else is being evaluated. Basically, the only if statement that matters is the last one, because it overwrites everything.

I recommend looking at [this](http://gameprogrammingpatterns.com/state.html), but stop after the Enum and Switches section.
